-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 11:07:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuarios` DEFAULT CHARACTER SET utf8 ;
USE `usuarios` ;

-- -----------------------------------------------------
-- Table `usuarios`.`Contraseñas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Contraseñas` (
  `id_contraseña` INT NOT NULL,
  `contraseña` VARCHAR(45) NULL,
  `fecha_modificacion` VARCHAR(45) NULL,
  `Contraseñascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contraseña`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Usuarios` (
  `id_usuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `nombre_usu` VARCHAR(45) NULL,
  `apellido_usu` VARCHAR(45) NULL,
  `fecha_nac_usu` VARCHAR(45) NULL,
  `n_telefono_usu` VARCHAR(45) NULL,
  `id_contraseña_usu` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuarios_Contraseñas_idx` (`id_contraseña_usu` ASC),
  CONSTRAINT `fk_Usuarios_Contraseñas`
    FOREIGN KEY (`id_contraseña_usu`)
    REFERENCES `usuarios`.`Contraseñas` (`id_contraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`deportes_sel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`deportes_sel` (
  `Usuarios_id_usuario` INT NOT NULL,
  `futbol` VARCHAR(45) NULL,
  `baloncesto` VARCHAR(45) NULL,
  `futbol_sala` VARCHAR(45) NULL,
  `balonmano` VARCHAR(45) NULL,
  INDEX `fk_deportes_sel_Usuarios1_idx` (`Usuarios_id_usuario` ASC),
  CONSTRAINT `fk_deportes_sel_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Metodo_pago` (
  `tarjeta` VARCHAR(16) NOT NULL,
  `cvv` INT(3) NULL,
  `fecha_caducidad` DATE NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`tarjeta`),
  INDEX `fk_Metodo_pago_Usuarios1_idx` (`Usuarios_id_usuario` ASC),
  CONSTRAINT `fk_Metodo_pago_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Transacciones` (
  `Usuarios_id_usuario` INT NOT NULL,
  `id_transaccion` INT NOT NULL,
  `importe` INT NULL,
  `fecha_transaccion` DATETIME NULL,
  PRIMARY KEY (`id_transaccion`, `Usuarios_id_usuario`),
  INDEX `fk_Transacciones_Usuarios1_idx` (`Usuarios_id_usuario` ASC),
  CONSTRAINT `fk_Transacciones_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
